### ISSUE TITLE
print_coinbase_tx_sum displays incorrect values

### ISSUE THREAD

**Issue by GeraltOfTrivia** [ryo-currency/ryo-currency#121]
If `print_coinbase_tx_sum` doesn't start from the genesis block, the values it produces are incorrect. 
Examples:
    
    print_coinbase_tx_sum 178400 20
    Sum of coinbase transactions between block heights [178400, 178420) is 18438044862.170624615 consisting of 18438044861.663124615 in emissions, and 0.507500000 in fees

    print_coinbase_tx_sum 0 5
    Sum of coinbase transactions between block heights [0, 5) is 100076.553572999 consisting of 100076.553572999 in emissions, and 0.000000000 in fees

**Comment by psychocrypt** [comment]
Thx for reporting: I found the issue and will create the bug fix pull request in a few ours.

**Comment by psychocrypt** [comment]
fixed with #122, this PR will be included in the next release
