### ISSUE TITLE
License copyright

### ISSUE THREAD

**Issue by jtgrassie** [ryo-currency/ryo-currency#135]
Just looked at LICENSE & ORIGINAL-LICENSE and the copyright Monero has been removed.

**Comment by jtgrassie** [comment]
Specifically you have removed:

```
Copyright (c) 2014-2018, The Monero Project

All rights reserved.
```

and

```
Parts of the project are originally copyright (c) 2012-2013 The Cryptonote
developers
```

**Comment by fireice-uk** [comment]
Thanks! First of all "the copyright Monero has been removed" is a nebulous term in this context, similar to "traffic law has been violated". I assume you are referring to [copyright notice](https://en.wikipedia.org/wiki/Copyright_notice).

The text of the `LICENSE` file is our own work, hence the notice. Monero copyright notice is retained in place (where appropriate). Putting a copyright notice on the licence terms would be saying that you wrote them yourself - are you sure you want me to do that?

**Comment by jtgrassie** [comment]
From the Monero license:

> 1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

The "above" copyright notice is now missing.

> 2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

Your redistributions also do not reproduce the copyright either.

Bottom line is this - the Monero project license covered code in the Monero project (whether individual source files had a copyright in them or not), the license stated copyright and credited the Cryptonote developers. This project is not giving that credit. Why not just keep the original license (unedited) alongside your new license?

**Comment by fireice-uk** [comment]
The text of the `LICENSE` file is our own work, hence the notice. Monero copyright notice is retained in place (where appropriate). Putting a copyright notice on the licence terms would be saying that you wrote them yourself - are you sure you want me to do that?

**Comment by jtgrassie** [comment]
The problem is that there are Monero source files without the copyright / license in the actual source code of those files, but was covered by Monero's LICENSE file. By removing / editing the original license, that copyright and license is not clear for those files. In fact, it appears as if this project is trying to claim copyright for files that are copyright Monero.

It would be nice if projects that base their work off of a very large amount of code from another project, the others project license / copyright is honored.

Given almost all the code here is from Monero, it may be more appropriate to keep the Monero license as the base license and for any new / modified code, by Ryo devs, apply your restrictions on top, just for those files. That would seem to me a solve to acknowledge the copyright / license of the forked code and still allow you to restrict your changes.

**Comment by fireice-uk** [comment]
> The problem is that there are Monero source files without the copyright / license in the actual source code of those files

I think you are confusing three separate legal concepts, I will point you to their respective Wikipedia pages, please read them thoroughly as they provide the minimum background for the discussion that you are attempting to do.

The three concepts are [licence](https://en.wikipedia.org/wiki/License), [copyright](https://en.wikipedia.org/wiki/Copyright)  and [copyright notice](https://en.wikipedia.org/wiki/Copyright_notice)

Putting them as "copyright / license" makes just about as much sense as "my house / rental agreement"

>  it may be more appropriate to keep the Monero license as the base license and for any new / modified code, by Ryo devs, apply your restrictions on top

That's not possible to do legally. A contract is either one thing or another. Fortunately your licence does not prohibit application of other licences. 

If you have any further questions / queries / requests, please do not hesitate to spell them out, but **please*** read the background first, it is extremely frustrating to try to decipher what you mean.

**Comment by jtgrassie** [comment]
I understand quite clearly the distinction between copyright and license. The reason I lumped them together in a "copyright / license" is because the Monero license explicitly states "must retain the above copyright notice", which you have removed.

It appears you are trying to assert that by keeping any existing _source code level_ copyright and license text satisfies the "above", but that is not the case. The Monero license stipulates the keeping of the copyright notice as written in the license file.

Just like every page in a book states copyright on one of the first few pages, they do not need to include that same copyright notice on every page in a book. You couldn't copy a chapter of a book and place it into another without a copyright notice somewhere (and of course in the case of most books, getting explicit permission to copy).

But anyway, I personally am not hugely bothered on this to have a long drawn out debate with you. 
It would just be a nice gesture to include that single line back into the ORIGINAL_LICENSE to simply credit and acknowledge the huge amount of work done by Monero developers (and CryptoNote developers if you added the final line back in too).

**Comment by fireice-uk** [comment]
> It appears you are trying to assert that by keeping any existing source code level copyright and license text satisfies the "above", but that is not the case. The Monero license stipulates the keeping of the copyright notice as written in the license file.

License file has no Monero work in it. Can you explain why you think Monero licence conditions apply to it?

> Just like every page in a book states copyright on one of the first few pages, they do not need to include that same copyright notice on every page in a book. 

Correct! Nevertheless we do it anyway (on top of the README.md and every single applicable file).

> It would just be a nice gesture to include that single line back into the ORIGINAL_LICENSE to simply credit and acknowledge the huge amount of work done by Monero developers (and CryptoNote developers if you added the final line back in too).

Putting a copyright notice on the licence terms would be saying that you wrote them yourself - are you sure you want me to do that? A simple yes is enough for that one, although I would kindly request that it is explicitly approved by someone higher up the food chain that can speak for the project as a whole like @fluffypony

**Comment by jtgrassie** [comment]
> Putting a copyright notice on the licence terms would be saying that you wrote them yourself - are you sure you want me to do that?

No. And that is your interpretation.

It is absolutely standard practice to include a copyright in the LICENSE or COPYING file in open source projects (such as in the [BSD license](https://en.wikipedia.org/wiki/BSD_licenses)). This is not declaring the license file _itself_ is copyright, but used to reference the _projects_ copyright and the license text refers to the _above_ copyright notice. The copyright notice is text in the license file referred to by the license terms.

**Comment by fireice-uk** [comment]
As I said. Just get @fluffypony to come here and say, "I would like you to put our copyright notice on top of the ORIGINAL_LICENSE file.", and we will make it so.

**Comment by jtgrassie** [comment]
Well I am not his keeper nor is he the owner of Monero as you well know. I'm simply giving my own personal viewpoint here as a FOSS supporter.

**Comment by fireice-uk** [comment]
Closing as per his own admission op is unauthorised to make requests on behalf of the copyright holder.

**Comment by fireice-uk** [comment]
Changed title to better reflect the nature of the ridiculous request.
