### ISSUE TITLE
Split transaction low fee issue

### ISSUE THREAD

**Issue by GeraltOfTrivia** [ryo-currency/ryo-currency#145]
A transaction that includes >33 receipients gets split in multiple transactions:

    No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y
    
    Transaction 1/2:
    Spending from address index 0
    
    Transaction 2/2:
    Spending from address index 0
    Sending 693.000000000.  Your transaction needs to be split into 2 transactions.  This will result in a transaction fee being applied to each transaction, for a total fee of 0.046000000
The second transaction fails to go through due to low fees, unless the fee is manually set to above normal:

    Transaction successfully submitted, transaction <72ee6aa7daabd25940479630b3aacb44ff628f9df6f39968f58307bb45d5e681>
    You can check its status by using the `show_transfers` command.
    Error: transaction <8cf49ed214340754c893033c88c17dddad6aff5ab39e4968f9ed53f521287101> was rejected by daemon with status: Failed
    Error: Reason: fee too low

**Comment by fireice-uk** [comment]
Self note: investigate for this milestone.

**Comment by fireice-uk** [comment]
Fix merged in #160
