### ISSUE TITLE
mined block failed verification

### ISSUE THREAD

**Issue by paulbrasted** [ryo-currency/ryo-currency#162]
I am trying to solo mine Ryo . To this end I have downloaded the latest ryo x64-0.3.2.0 windows 10
and am running

 ..\RyoWallet\resources\bin\ryod --data-dir=E:\ryo --rpc-bind-port 12211 --confirm-external-bind

 for the daemon and 

..\RyoWallet\resources\bin\ryo-wallet-rpc --daemon-address 127.0.0.1:12211 --rpc-bind-ip 192.168.0.22 --rpc-bind-port 12212 --confirm-external-bind --disable-rpc-login --shared-ringdb-dir e:\ryo\.shared-ringdb --wallet-file xxxxxxxx --prompt-for-password  --trusted-daemon --log-file rpc.log --log-level 4

for the rpc wallet.

I am running this on windows 10 machines on my home network 

Everything is synchronized and when I mine on a pool using xmr-stak-2.7.0 I can see my payments coming through via the logs of the rpc-wallet

In an attempt to solo mine I downloaded  

https://github.com/dvandal/cryptonote-nodejs-pool .

I have managed to run this using nodejs under ubuntu (WSL) for windows and  make the necessary connections to ryod and ryo-wallet-rpc  and every thing seems to run and connect OK. I then use xmr-stak-2.7.0 to connect to the cryptonote-nodejs-pool . This set up is across two windows machines on my home network.

Twice now though I have managed to discover a block only to have this error message appear in my
ryod.log.

2019-01-05 00:31:59.115	[RPC0]	ERROR	default	src/cryptonote_core/cryptonote_core.cpp:1093	mined block failed verification

Xmr-stak shows the best result way above the required difficulty of the network and a corresponding received share is shown in the pool log  with the same times ...

suffice to say I did not receives any payments. As you can guess this is extremely frustrating !!
Any clues anybody where to look as to  what is going on here and am I asking the right people? Is this a fault with royd or the pool software or indeed with xmr-stak….

Thanks for any help

**Comment by paulbrasted** [comment]
thanks for prompt reply ..ill give it a go....

**Comment by paulbrasted** [comment]
So I down loaded the master zip , expanded and copied into a host directory in ubuntu, did npm update which complied ok . I then used your example ryo.json where i changed to my wallet address and forks =1   and  my address of daemon and rpc -wallet. It all went ok and ran and I looked in redis--browser to see the ok connections.

but as soon as I try and connect xmr-stak to your pool I get the following


2019-01-05 19:36:17 [pool] (Thread 1) Malformed message from ::ffff:192.168.0.22 generated an exception. Message: {"method":"login","params":{"login":"RYoLsfJesRvfCL7vi8jsTxSJjercivPh6NoFD4VbgTf9hfJTw6JekVBiwqs7ebqSq5FrwsxYcTjsGBaCRQasSvGZJWiQ6xXomum","pass":"x","rigid":"","agent":"xmr-stak/2.7.0/70b819386/unknown/win/amd-cpu/20"},"id":1}
2019-01-05 19:36:17 [pool] (Thread 1) Exception: Command failed: bin/ryo-address-validator RYoLsfJesRvfCL7vi8jsTxSJjercivPh6NoFD4VbgTf9hfJTw6JekVBiwqs7ebqSq5FrwsxYcTjsGBaCRQasSvGZJWiQ6xXomum RYoLsfJesRvfCL7vi8jsTxSJjercivPh6NoFD4VbgTf9hfJTw6JekVBiwqs7ebqSq5FrwsxYcTjsGBaCRQasSvGZJWiQ6xXomum
/bin/sh: 1: bin/ryo-address-validator: not found

If I look in bin of the hosting directory there is nothing there ?

**Comment by mosu-forge** [comment]
I forgot to mention one thing, you need to copy the ryo-address-validator bin file from the daemon release into that bin folder. Then you should be able to validate logins

**Comment by paulbrasted** [comment]
Ok ..My deamon is running on wndows at moment ..I will down load the Linux release ..hoping it will run ..Otherwise I guess I will have to download ryo source and build under WSL ubuntu …

I know it sounds confusing but I have had to use two machines

**Comment by mosu-forge** [comment]
If you are just going to solo mine, and not allow others on your pool, you could change this line: https://github.com/mosu-forge/cryptonote-nodejs-pool/blob/master/lib/utils.js#L51

Remove `var info = runValidatorTool(address);`  and replace with `return true;` and then also on line 61 replace the same line with `return false;`

You may also want to disable the payments module, as there's no point in making a transfer from yourself to the same wallet. Just set this line in your pool config to false: https://github.com/mosu-forge/cryptonote-nodejs-pool/blob/master/config_examples/ryo.json#L108

And make sure to restart the pool.

**Comment by paulbrasted** [comment]
I download the Linux command line wallet and copied over the address validator and all works ok ..
Thank you for your help.   I will take  a look at the suggested edits and wait and see what happens on a  mined block !!

Am thinking it is pretty stupid that I did not try all this  out on testnet ..is it a matter of changing parameters to daemons so that I may run it all on a chain of reduced difficulty .

**Comment by mosu-forge** [comment]
There’s a very small chance of orphan blocks, but at this point you know you have it set up correctly.

Thanks for deciding to mine solo, if there’s every any other questions feel free to join out Telegram or Discord channel.

**Comment by fireice-uk** [comment]
Closing as resolved.

**Comment by mosu-forge** [comment]
@paulbrasted by the way, I realize I don't have you on our pool list contacts, you must upgrade to the pool for our 0.4.0.0 fork: https://www.reddit.com/r/ryocurrency/comments/anhajn/ryo_0400_pool_upgrade_procedure/
