### ISSUE TITLE
Lack of blockchain.raw bootstrap import information.

### ISSUE THREAD

**Issue by LeadManPL** [ryo-currency/ryo-currency#178]
[Releases page](https://github.com/ryo-currency/ryo-currency/releases) contains link to download [blockchain.raw](https://download.ryo-currency.com/blockchain.raw) , but there is no instruction how to import RAW blockchain into freshly installed gui-wallet.
I searched for instructions in following places:
* https://github.com/ryo-currency
* https://github.com/ryo-currency/ryo-wallet
* https://www.reddit.com/r/ryocurrency/comments/9e9mw3/ryo_wallet_atom_architected_from_scratch/
* https://bitcointalk.org/index.php?topic=4413010.0
* https://github.com/ryo-currency/ryo-gui-wallet
* https://ryo-currency.com/faq/

Not a single word of importing blockchain bootstrap in these places. Any Hints?

**Comment by fireice-uk** [comment]
If you have trouble, run `ryod` - it will sync on its own
the command used to import is `ryo-blockchain-import`

**Comment by sobertram** [comment]
This is for monero but it is the same for ryo. I just followed the instructions for linux and its working.

https://monero.stackexchange.com/questions/7788/which-directory-does-monero-blockchain-import-by-default-use-to-store-the-impo/

**Comment by LeadManPL** [comment]
@fireice-uk @sobertram thanks for the info.
I leave this issue open, as it relates to general lack of information about import. (will fix title)
It's up to you when to close this issue.
