### ISSUE TITLE
"Failed to get random outs" when sending

### ISSUE THREAD

**Issue by aleqx** [ryo-currency/ryo-currency#200]
Using the latest Winx64 GUI wallet downloaded just now (Version: ATOM v1.3.2-v0.4.0.1) and just tried to send funds to Tradeogre using all default settings. I tried both the integrated address and also wallet+payment_id address. Both are failing. The GUI wallet says:

"Failed to get random outs"

I'm using a remote daemon geo.ryoblocks.com:12211 and the wallet is sync'ed (height 275952 on both wallet and node).

Has this project died entirely or is this a bug?

**Comment by mosu-forge** [comment]
The project is far from dead.

I would try sending a smaller amount, it is possible you are trying to spend a lot of tiny inputs. As mentioned on Discord, try sending a smaller amount of coins first and see if that works.
