### ISSUE TITLE
Compile Error on Raspberry Pi 2 B

### ISSUE THREAD

**Issue by BrainZap** [ryo-currency/ryo-currency#218]
EDIT - FIXED:  SEE NEXT COMMENT.

I keep getting hung up on the following error while trying to compile on a Raspberry Pi 2 B.  

![RYOERRss](https://user-images.githubusercontent.com/7952421/64971373-74d1ad00-d85c-11e9-8f71-ade9229ff594.png)

**Comment by BrainZap** [comment]
Fixed it myself.  Someone might want to update the file as follows:

/ryo-currency/src/cryptonote_basic/account.cpp  
line 185
  
REPLACE LINE 185:  memset(&fake, 0, sizeof(fake));
WITH:   memset(&unwrap(fake), 0, sizeof(fake));

I'm still compiling so there might be more issues, but for now I've gotten by this one.  YW.

**Comment by psychocrypt** [comment]
thanks for the update and fix

**Comment by BrainZap** [comment]
Fix found on Monero github.  [https://github.com/monero-project/monero/pull/3851/files](url)
