### ISSUE TITLE
Compile Error #2 Raspberry Pi B

### ISSUE THREAD

**Issue by BrainZap** [ryo-currency/ryo-currency#219]
I have not be able to figure this one out.

![RYOERRss2](https://user-images.githubusercontent.com/7952421/65060361-8f735700-d92c-11e9-8ca2-c3455ed718cb.jpg)

**Comment by fireice-uk** [comment]
That one is odd. Ty "make clean" first, if this doesn't help pastebin the whole lot, the error might be above.

**Comment by BrainZap** [comment]
make clean fixed this issue.  Thanks!
