### ISSUE TITLE
cli-wallet for raspberry pi.

### ISSUE THREAD

**Issue by kitchen-bear** [ryo-currency/ryo-currency#247]
Hi there!
This issue is for 
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
raspberry pi 3.
Problem: cli-wallet can not send the money.
bc is attached to the raspi via 32gb usb-flash.
I can see the incoming money, but during the sending procedure 
I've got problems with daemon (no connection). 
Below is output from --log-level=4
[raspi_err_edited.txt](https://github.com/ryo-currency/ryo-currency/files/4676962/raspi_err_edited.txt)

**Comment by Ryo-RU** [comment]
what needs working out:
- binary is compiled without any errors? (exclude compiling errors and glitching binary as a result)
- usb (hardware problem), have you tried another media? (make sure that in both cases you have enough free space)
- can you create a new wallet address from scratch on pi3, send there 1test coin from your main wallet (from for example windows, or whatever wallet) and try to log into test wallet and do the tx?

**Comment by kitchen-bear** [comment]
>     * binary is compiled without any errors? (exclude compiling errors and glitching binary as a result)

1st time - forget about zram and had errors, after installing - everything was fine according with compiling manual.
> 
>     * usb (hardware problem), have you tried another media? (make sure that in both cases you have enough free space)

Yep, space is enough. BC takes about 60% of usb-flash media on exFAT partition, service for this kind fs was included. In other case - usb-stick will be invisible.
 
>     * can you create a new wallet address from scratch on pi3, send there 1test coin from your main wallet (from for example windows, or whatever wallet) and try to log into test wallet and do the tx?
yep. the wallet is made from scratch on this raspi device after compiling was done.

**Comment by kitchen-bear** [comment]
some update: I have checked whether the issue is due to libboost - reinstall dependencies, installed libboost and compiled everything one more time again. Finally - there is no changes. If I use cli-wallet with remote node syncing - it works very fast, and can send and receive coins. If I use it with local BC, it works very slow, the problems remains the same...

**Comment by kitchen-bear** [comment]
Finally! Solution have been found!
The reason of issue - is heavy reading of non-native file systems (exFAT, vfat, ntfs, etc) by Raspbian/Linux. 

1st it is necessary to make a linux partition and format usb-flash.
the example is right here:
https://www.tecmint.com/create-new-ext4-file-system-partition-in-linux/

2nd it is necessary to place on media blockchain (17 GB+) and make owner
of file the same group and user with the wallet:
i.e.:
sudo chown pi:pi *.mdb

After that cli-wallet can work in the normal mode.

I think the issue can be closed now.
Problem is solved.
