### ISSUE TITLE
Integrating RYO on decentralised exchanges question

### ISSUE THREAD

**Issue by LeadManPL** [ryo-currency/ryo-currency#257]
I have checked [RYO RoadMap](https://ryo-currency.com/#roadmap) and other parts of webpage and do not find any mention about any decentralised exchange that would allow to trade RYO.

Is there remote chance, that RYO can be traded on decentralized exchanges that do not require registration nor KYC? After all, privacy is main target of RYO, isn't it? And how am I suposed to feel that privacy if there is still no way to trade RYO ''privately'?

I am not sure if you blockchain is capable of using / implementing **0x** protocol, but maybe there is some other technology that could be implemented to achieve this?

And final thought, having RYO on only one exchange ([FAQ](https://ryo-currency.com/faq/) mentions only crex24) is bad idea IMHO. If RYO was easier accessible on more exchanges its price could rise, and thus dev fund would get bigger ;)

If this is too hard to achieve, maybe something like [BISQ](https://bisq.network/), which I recently discovered, could be an option?

**Comment by Nostradamus411** [comment]
It was a conscious decision to only list Crex24 on the FAQ page as it's a registered business.  RYO is also available for trading at TradeOgre which does not require any KYC but is an unknown entity which can carry the potential of added risk for users so it wasn't included in the FAQ page.  

Additionally RYO was available on BISQ after being added with [PR #1665](https://github.com/bisq-network/bisq/pull/1665).

**Comment by LeadManPL** [comment]
Thanks for swift response, I was not aware that BISQ lists RYO, thus closing. If you know about any other decentralized exchange that lists RYO, please leave a comment.

**Comment by LeadManPL** [comment]
Actually BISQ has de-listed RYO due to inactivity :(

Does anyone know of some other DEX that lists RYO?
