### ISSUE TITLE
Is there a CLI/RPC wallet working under Ubuntu 16.04 Server?

### ISSUE THREAD

**Issue by cotinco** [ryo-currency/ryo-currency#53]
I compiled daemon and client under Ubuntu 16.04 Server; daemon works fine, but CLI and RPC wallets behave very strange. The CLI wallet is able to restore SUMO wallet and create new wallet, but when I try to sweep my balance to the new wallet, it shows error "wallet failed to connect to daemon: http://localhost:12211. Daemon either is not started or wrong port was passed. Please make sure daemon is running or change the daemon address using the 'set_daemon' command". Then it starts to show "(out of sync)" is the prompt.
When I start RPC wallet, it behaves exactly as in issue "https://github.com/monero-project/monero/issues/4072", but it is unable to do any transaction (error "wallet2.cpp:1708:N5tools5error23no_connection_to_daemonE: no connection to daemon, request = getblocks.bin").
When I start CLI wallet after a long pause, it resyncs wallet with the blockchain, but still fails to do any operation.
If I do any RPC daemon operations manually via its RPC port 12211, they all work. But I'm unable to do any client operations.
Is it a bug? Do you have a working fix for that?

**Comment by psychocrypt** [comment]
Could you please check if you still have the behavior with the current dev version. If possible please recreate your wallet from the seed (avoid #48)

**Comment by cotinco** [comment]
The same error (commit bf1059aaeeece1bf17bb22b53cbf9c32a4ff138d). Daemon restarted to new version, wallet recreated from seed and showed old SUMO balance, but failed to sweep. I have completely no idea what's wrong :(

**Comment by cotinco** [comment]
Follow-up: after a few restarts, RPC wallet works exactly as in referenced monero issue while continuing spamming with "no connection to daemon", but I'm afraid it will end exactly as in referenced issue (after a day or two it will require restart again and again).

**Comment by KyleFromOhio** [comment]
I get same thing. No matter what the configuration is (local ip or private ip and/or rpc login or no login). Calls seem to work fine but every 20-40 seconds my log is filled with...

`2018-07-25 23:36:17.023	[RPC0]	ERROR	net.http	contrib/epee/include/net/http_client.h:397	HTTP_CLIENT: Failed to SEND`
`2018-07-25 23:36:17.023	[RPC0]	ERROR	wallet.wallet2	src/wallet/wallet2.cpp:1699	!r. THROW EXCEPTION: error::no_connection_to_daemon`
`2018-07-25 23:36:17.023	[RPC0]	WARN 	net.http	src/wallet/wallet_errors.h:794	/DISTRIBUTION-BUILD/src/wallet/wallet2.cpp:1699:N5tools5error23no_connection_to_daemonE: no connection to daemon, request = getblocks.bin`

**Comment by psychocrypt** [comment]
mhh I can not find the issue and monero not linked the fix. I am still on it.

**Comment by malbit** [comment]
I had the same problem at Arqma and after code tracing I did figure it out one thing. 
Look at: 
https://github.com/ryo-currency/ryo-currency/blob/dcea05a5251e0e649bafc55638d7cf3b8ecfeb5a/src/wallet/wallet2.cpp#L136
and I would change that Blockchain Height. It did help for us at STAGENET while testing v0.2.0.0 daemon.
Simply wallet is gonna stuck because didn’t do blocks segregation :)

**Comment by fireice-uk** [comment]
@malbit This is correct for mainnet (time of sumo - ryo fork), and will work on testnet. It might need a proper implementation for stagenet and private forks.

**Comment by malbit** [comment]
Yes. But below that you have testnet and stagenet. Wallet did not fork form me until I did change stagenet values to those which I had on stagenet.
My issues where:
1. No wallet refresh until rescan_bc and restarted.
2. Wallet-rpc exactly the same.
