### ISSUE TITLE
Wallet RPC: Feature Requests

### ISSUE THREAD

**Issue by mosu-forge** [ryo-currency/ryo-currency#68]
It would be very beneficial to have the following features:

* Restore & open a wallet by seed words or private keys  
* The ability to create a Kurz wallet via RPC  
* The ability to pass a height to the rescan_bc function

**Comment by fireice-uk** [comment]
Implemented in #85 and #91 ability to create kurz wallets was in already.

**Comment by mosu-forge** [comment]
Great, I will implement these into the working branch

**Comment by mosu-forge** [comment]
One more feature request:

Add `shutdown: false` optional parameter to `stop_wallet` command to close the currently opened wallet file, but not shutdown the whole RPC server.

Use case: when user of GUI closes the open file and returns to the wallet select screen, we should fully close the wallet from RPC until the next file is opened.
