### ISSUE TITLE
FORK_FEE_V2 is different for mainnet and testnet

### ISSUE THREAD

**Issue by minerrocks** [ryo-currency/ryo-currency#78]
https://github.com/ryo-currency/ryo-currency/blob/59a7b4ce2c1d1f02567fbcd009e337d19a87d345/src/cryptonote_config.h#L187

FORK_FEE_V2 is different for mainnet and testnet
For testnet it is set from block version of 6
For mainnet it is set from block version of 5

We run private mainnet to test fork V5, and appeared that payments are broken through rpc calls.
With `unimportant priority` - `{"code":-19,"message":"not enough outputs to use Please use sweep_dust."}`. But there no dust and no command `sweep_dust` in wallet-cli.
With `normal priority` - `{"code":-4,"message":"transaction was rejected by daemon"}`

Using wallet-cli with `unimportant` priority tx of 1 RYO failed with error `Fee too low`.
Using wallet-cli with `normal` priority tx of 1 RYO passed.

**Comment by fireice-uk** [comment]
That's correct. Testnet gets forked more often than mainnet so we can implement a feature from v5 on mainnet while from v6 on testnet, just like you said. You need to make sure your nettype and version matches your intent.
